spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: microservicecloud-eureka-client-dev
---
spring:
    profiles: test
    application:
        name: microservicecloud-eureka-client-test
---
spring:
    profiles: uat
    application:
        name: microservicecloud-eureka-client-uat